version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the React app...
      - npm run build
  post_build:
    commands:
      - echo Build completed.
      - echo Syncing files to S3...
      - aws s3 sync dist/ s3://wordscape-customer-frontend --delete
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id EASZXNEY3HUAC --paths "/*"
