GET  http://localhost:8081/orders
Content-Type: application/json

### Retrieving Orders ###

GET  http://localhost:8081/orders/4
Content-Type: application/json

### Retrieve Progress
GET http://localhost:8081/projectTracking/4
Content-Type: application/json


### Retrieve papers
GET http://localhost:8081/papers
Content-Type: application/json

### Get All Orders
GET http://localhost:8081/orders
Content-Type: application/json

### Job Card Order
GET http://localhost:8081/jobCard/4
Content-Type: application/json

### Get Customer Order
GET http://localhost:8081/orders/customer/
Content-Type: application/json

### Get ALL Orders
GET http://localhost:8081/orders
Content-Type: application/json

### Get Orders Page Data
GET http://localhost:8081/orders?pageNumber=0
Content-Type: application/json

### Get all Customers
GET http://localhost:8081/customers
Content-Type: application/json

### Get Job Card Orders
GET http://localhost:8081/jobCard/4
Content-Type: application/json

### Retrieve Users
GET http://localhost:8081/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlcyI6WyJST0xFX0FETUlOIl0sImlkIjoxLCJleHAiOjE3MTg4OTAxMzEsImlhdCI6MTcxODgwMzczMX0.Pa5cOqggU4L9jd9NqJ6wTIN94jHCFeDI4lF4JGuKGZUDUD4JkBsy8UqL_1jszq7h1Od2yn4RAuZJp8sSFaaJSg

### Retrieve Sheet Sizes
GET https://erp-api.wordscapepress.com/sheetSizes