GET  http://localhost:8081/orders
Content-Type: application/json

### Retrieving Orders ###

GET  http://localhost:8081/orders/4
Content-Type: application/json

### Retrieve Progress
GET http://localhost:8081/projectTracking/4
Content-Type: application/json


### Retrieve papers
GET http://localhost:8081/papers
Content-Type: application/json

### Get All Orders
GET http://localhost:8081/orders
Content-Type: application/json

### Job Card Order
GET http://localhost:8081/jobCard/4
Content-Type: application/json

### Get Customer Order
GET http://localhost:8081/orders/customer/2
Content-Type: application/json

### Get ALL Orders
GET http://localhost:8081/orders
Content-Type: application/json

### Get Orders Page Data
GET http://localhost:8081/orders?pageNumber=0
Content-Type: application/json


